services:
  - type: web
    name: bodega-aseo-colegio
    runtime: python
    pythonVersion: "3.11.9"
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_EMAIL
        value: bodega@colegio.cl
      - key: ADMIN_PASS
        value: bodega2025
